package dns

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/c0m4r/nic/internal/executor"
)

const resolvConf = "/etc/resolv.conf"

// WriteResolvConf writes nameservers to /etc/resolv.conf.
func WriteResolvConf(nameservers []string) error {
	if len(nameservers) == 0 {
		return nil
	}

	if executor.DryRun {
		fmt.Printf("[dry-run] write %s with nameservers: %s\n",
			resolvConf, strings.Join(nameservers, ", "))
		return nil
	}

	// Remove immutable flag before writing
	_ = Unguard()

	var sb strings.Builder
	sb.WriteString("# Generated by nic - do not edit\n")
	for _, ns := range nameservers {
		sb.WriteString("nameserver ")
		sb.WriteString(ns)
		sb.WriteByte('\n')
	}

	if err := os.WriteFile(resolvConf, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("write %s: %w", resolvConf, err)
	}

	return nil
}

// Guard makes /etc/resolv.conf immutable to prevent other tools from modifying it.
func Guard() error {
	if executor.DryRun {
		fmt.Printf("[dry-run] chattr +i %s\n", resolvConf)
		return nil
	}
	if !executor.CommandExists("chattr") {
		return nil // Silently skip if chattr not available
	}
	_, err := executor.Run("chattr", "+i", resolvConf)
	return err
}

// Unguard removes the immutable flag from /etc/resolv.conf.
func Unguard() error {
	if !executor.CommandExists("chattr") {
		return nil
	}
	cmd := exec.Command("chattr", "-i", resolvConf)
	_ = cmd.Run() // Ignore errors (file might not be immutable)
	return nil
}

// CurrentNameservers reads current nameservers from /etc/resolv.conf.
func CurrentNameservers() []string {
	f, err := os.Open(resolvConf)
	if err != nil {
		return nil
	}
	defer func() { _ = f.Close() }()

	var servers []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "nameserver ") {
			ns := strings.TrimSpace(strings.TrimPrefix(line, "nameserver "))
			if ns != "" {
				servers = append(servers, ns)
			}
		}
	}
	return servers
}
