package dns

import (
	"bufio"
	"fmt"
	"net"
	"os"
	"strings"

	"github.com/c0m4r/nic/internal/executor"
)

var resolvConf = "/etc/resolv.conf"

type Snapshot struct {
	Captured  bool        `json:"captured"`
	Exists    bool        `json:"exists"`
	Content   []byte      `json:"content,omitempty"`
	Mode      os.FileMode `json:"mode,omitempty"`
	Immutable bool        `json:"immutable,omitempty"`
}

// WriteResolvConf writes nameservers to /etc/resolv.conf.
func WriteResolvConf(nameservers []string) error {
	if len(nameservers) == 0 {
		return nil
	}

	if executor.DryRun {
		fmt.Printf("[dry-run] write %s with nameservers: %s\n",
			resolvConf, strings.Join(nameservers, ", "))
		return nil
	}

	// Remove immutable flag before writing
	if err := Unguard(); err != nil {
		return fmt.Errorf("unguard %s: %w", resolvConf, err)
	}

	var sb strings.Builder
	sb.WriteString("# Generated by nic - do not edit\n")
	for _, ns := range nameservers {
		if net.ParseIP(ns) == nil {
			return fmt.Errorf("invalid nameserver %q", ns)
		}
		sb.WriteString("nameserver ")
		sb.WriteString(ns)
		sb.WriteByte('\n')
	}

	if err := os.WriteFile(resolvConf, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("write %s: %w", resolvConf, err)
	}

	return nil
}

// Capture records the resolver contents and protection state for rollback.
func Capture() (Snapshot, error) {
	info, err := os.Stat(resolvConf)
	if errorsIsNotExist(err) {
		return Snapshot{Captured: true}, nil
	}
	if err != nil {
		return Snapshot{}, err
	}
	content, err := os.ReadFile(resolvConf)
	if err != nil {
		return Snapshot{}, err
	}
	snapshot := Snapshot{Captured: true, Exists: true, Content: content, Mode: info.Mode().Perm()}
	if executor.CommandExists("lsattr") {
		fields := strings.Fields(executor.RunSilent("lsattr", "-d", resolvConf))
		if len(fields) > 0 && strings.Contains(fields[0], "i") {
			snapshot.Immutable = true
		}
	}
	return snapshot, nil
}

// Restore puts back the resolver state captured before nic made changes.
func Restore(snapshot Snapshot) error {
	if !snapshot.Captured {
		return nil
	}
	if executor.DryRun {
		fmt.Printf("[dry-run] restore %s\n", resolvConf)
		return nil
	}
	if err := Unguard(); err != nil {
		return err
	}
	if !snapshot.Exists {
		if err := os.Remove(resolvConf); err != nil && !errorsIsNotExist(err) {
			return err
		}
		return nil
	}
	if err := os.WriteFile(resolvConf, snapshot.Content, snapshot.Mode); err != nil {
		return fmt.Errorf("restore %s: %w", resolvConf, err)
	}
	if err := os.Chmod(resolvConf, snapshot.Mode); err != nil {
		return fmt.Errorf("restore mode for %s: %w", resolvConf, err)
	}
	if snapshot.Immutable {
		if err := Guard(); err != nil {
			return fmt.Errorf("restore immutable flag: %w", err)
		}
	}
	return nil
}

func errorsIsNotExist(err error) bool {
	return err != nil && os.IsNotExist(err)
}

// Guard makes /etc/resolv.conf immutable to prevent other tools from modifying it.
func Guard() error {
	if executor.DryRun {
		fmt.Printf("[dry-run] chattr +i %s\n", resolvConf)
		return nil
	}
	if !executor.CommandExists("chattr") {
		return nil // Silently skip if chattr not available
	}
	_, err := executor.Run("chattr", "+i", resolvConf)
	return err
}

// Unguard removes the immutable flag from /etc/resolv.conf.
func Unguard() error {
	if !executor.CommandExists("chattr") {
		return nil
	}
	_, err := executor.Run("chattr", "-i", resolvConf)
	if err != nil {
		message := strings.ToLower(err.Error())
		for _, benign := range []string{"operation not supported", "inappropriate ioctl", "not supported"} {
			if strings.Contains(message, benign) {
				return nil
			}
		}
	}
	return err
}

// CurrentNameservers reads current nameservers from /etc/resolv.conf.
func CurrentNameservers() []string {
	f, err := os.Open(resolvConf)
	if err != nil {
		return nil
	}
	defer func() { _ = f.Close() }()

	var servers []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "nameserver ") {
			ns := strings.TrimSpace(strings.TrimPrefix(line, "nameserver "))
			if ns != "" {
				servers = append(servers, ns)
			}
		}
	}
	return servers
}
